In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(np.random.randint(0,33,10).reshape(5,2),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2"],dtype=int)

In [4]:
df.head()

      Column1  Column2
Row1       10       17
Row2       25       18
Row3        0        2
Row4        4       23
Row5       17       29

In [5]:
df.to_csv('Test1.csv')

In [6]:
#Accesing the elements
##1. .loc only row location ,2.  .iloc location both row and column
df.loc['Row1']
type(df.loc['Row1'])

pandas.Series

In [7]:
#when there is only row and 0 in the column then it is dataseries otherwise it is dataframe
df.iloc[1:4,0]
df.iloc[1:4,:1]

      Column1
Row2       25
Row3        0
Row4        4

In [8]:
df.at["Row1","Column1"]

np.int64(10)

In [9]:
df.shape

(5, 2)

In [10]:
df.values#this returns the dataframe in an array form

array([[10, 17],
       [25, 18],
       [ 0,  2],
       [ 4, 23],
       [17, 29]])

In [11]:
df.isnull().sum()

Column1    0
Column2    0
dtype: int64

In [12]:
df.value_counts()#tells which element is present how many times

Column1  Column2
10       17         1
25       18         1
0        2          1
4        23         1
17       29         1
Name: count, dtype: int64

In [13]:
df['Column1'].unique()#only returns unique values and not repeated ones only in one column

array([10, 25,  0,  4, 17])

In [14]:
df = pd.read_csv(r"C:\Users\chava\Downloads\netflix_titles.csv.zip")

In [15]:
df.head

<bound method NDFrame.head of      show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]>

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [17]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [18]:
df.value_counts("country")

country
United States                                    2818
India                                             972
United Kingdom                                    419
Japan                                             245
South Korea                                       199
                                                 ...
Russia, Spain                                       1
Croatia, Slovenia, Serbia, Montenegro               1
Japan, Canada                                       1
United States, France, South Korea, Indonesia       1
United Arab Emirates, Jordan                        1
Name: count, Length: 748, dtype: int64

In [19]:
df[df["type"]=="TV Show"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [20]:
#data series
s=pd.Series([23,45,67,8])
print(s)
print(type(s))
#indexing
print(s[2])
print(s.index)

0    23
1    45
2    67
3     8
dtype: int64
<class 'pandas.Series'>
67
RangeIndex(start=0, stop=4, step=1)

In [21]:
#data series
s2 = pd.Series([35,90,88,0,None])
s2["e"]=90
print(s2)
#custom indexing
#print(s2["b"])

0    35.0
1    90.0
2    88.0
3     0.0
4     NaN
e    90.0
dtype: float64

In [22]:
#vectorized operation 
s1 = pd.Series([60,9,0,33,2])
print(s1 +s2)

0    95.0
1    99.0
2    88.0
3    33.0
4     NaN
e     NaN
dtype: float64

In [23]:
changed_s = s.drop(2)
print(changed_s)
print(s)

0    23
1    45
3     8
dtype: int64
0    23
1    45
2    67
3     8
dtype: int64

In [35]:
info = {
    "name": ["Sh","Ka","Vidhi"],
    "Marks":[23,45,None],
    "Grade":["A+","B",None]
}
i = pd.DataFrame(info)
print(info)
print(i)
print(type(i))
print(df.index)
print(df.columns)
np_array=np.array([[1,2,3],[4,None,6],[7,8,9]])
nf = pd.DataFrame(np_array,index=["Row1","Row2","Row3"],columns=["Column1","Column2","Column3"])
print(nf)
list=[["p",78,800],["n",89,900],["o",69,450]]
df = pd.DataFrame(list,columns=["name","marks","Ageregate"])
print(df)

{'name': ['Sh', 'Ka', 'Vidhi'], 'Marks': [23, 45, None], 'Grade': ['A+', 'B', None]}
    name  Marks Grade
0     Sh   23.0    A+
1     Ka   45.0     B
2  Vidhi    NaN   NaN
<class 'pandas.DataFrame'>
Index(['person1', 'person2', 'person3', 'person4', 'person5'], dtype='str')
Index(['name', 'age', 'country', 'salary'], dtype='str')
     Column1 Column2 Column3
Row1       1       2       3
Row2       4    None       6
Row3       7       8       9
  name  marks  Ageregate
0    p     78        800
1    n     89        900
2    o     69        450

In [45]:
print(nf.nunique())
print(nf.describe())
print(nf.info())
print(nf.sample())

Column1    3
Column2    2
Column3    3
dtype: int64
        Column1  Column2  Column3
count         3        2        3
unique        3        2        3
top           1        2        3
freq          1        1        1
<class 'pandas.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  3 non-null      object
 1   Column2  2 non-null      object
 2   Column3  3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes
None
     Column1 Column2 Column3
Row1       1       2       3

In [37]:
#indexing
type(df["name"])
nf[['Column1', 'Column2']]

     Column1 Column2
Row1       1       2
Row2       4    None
Row3       7       8

In [38]:
nf.loc["Row1"]
print(nf["Column3"])
nf.iloc[0:2,0:2]
df.at[0,"name"]
df.iat[2,1]

Row1    3
Row2    6
Row3    9
Name: Column3, dtype: object

np.int64(69)

In [39]:
#Filtering
df[(df["marks"]>70)&(df["Ageregate"]>800)]
df.query("marks>50 and Ageregate <900")

  name  marks  Ageregate
0    p     78        800
2    o     69        450

In [40]:
data=[["Raju",None,"India",50000],["Sham",49,"India",90000],["Ram",25,None,50000],["Sam",32,"phillipines",50000],["Anjali",32,"UK",550000]]
df=pd.DataFrame(data,index=["person1","person2","person3","person4","person5"],columns=["name","age","country","salary"])
print(df)

           name   age      country  salary
person1    Raju   NaN        India   50000
person2    Sham  49.0        India   90000
person3     Ram  25.0          NaN   50000
person4     Sam  32.0  phillipines   50000
person5  Anjali  32.0           UK  550000

In [41]:
#Data Cleaning
df.isnull()
df.isnull().sum()
df.dropna()
df.dropna(axis=1)
df.fillna(0)
#df["age"]=df["age"].fillna(df["age"].mean())
df.ffill()
df.bfill()

           name   age      country  salary
person1    Raju  49.0        India   50000
person2    Sham  49.0        India   90000
person3     Ram  25.0  phillipines   50000
person4     Sam  32.0  phillipines   50000
person5  Anjali  32.0           UK  550000

In [42]:
df.duplicated()
df.duplicated(["age","country"])

person1    False
person2    False
person3    False
person4    False
person5    False
dtype: bool

In [43]:
df.drop_duplicates(["age"])

         name   age      country  salary
person1  Raju   NaN        India   50000
person2  Sham  49.0        India   90000
person3   Ram  25.0          NaN   50000
person4   Sam  32.0  phillipines   50000

In [44]:
#changing Datatypes
print(df["age"].astype(str))
date_str="11-01-2023"
date=pd.to_datetime(date_str)
print(date)

person1     NaN
person2    49.0
person3    25.0
person4    32.0
person5    32.0
Name: age, dtype: str
2023-11-01 00:00:00